image: docker:latest

variables:
  KUBE_ENV: "production" # название окружения в GitLab

before_script:
  - apk add --no-cache curl
  - curl -LO "https://github.com/bitnami/kubectl-bin/releases/download/v1.20.6/kubectl-linux-amd64" && chmod +x ./kubectl-linux-amd64 && mv ./kubectl-linux-amd64 /usr/local/bin/kubectl
  - echo "$KUBECONFIG" | base64 -d > /builds/$CI_PROJECT_PATH/kubeconfig.yaml
  - export KUBECONFIG="$PWD/kubeconfig.yaml"

stages:
  - build
  - test
  - deploy_staging
  - deploy_production

build:
  stage: build
  script:
    - echo 'Build success!'
test:
  stage: test
  script:
    - echo 'Test success!'

deploy_staging:
  stage: deploy_staging
  script:
    - echo 'Deploy staging  success!'

deploy_production:
  stage: deploy_production
  script:
    - echo 'Deploy production success!'