variables:
  KUBE_CONTEXT: borisey/kubernetes:kubernetes-connection

stages:
  - build
  - test
  - deploy_staging
  - deploy_production

build:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/borisey/kubernetes/sample:latest .
    - docker push $CI_REGISTRY/borisey/kubernetes/sample:latest
    - echo "Image built"

test:
  image: docker
  stage: test
  services:
    - docker:dind
  script:
    - echo "Tests completed successfully!"

deploy_staging:
  stage: deploy_staging
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl get pods
    - kubectl get nodes -o wide
    - echo "Deployment LOGIN-APP to K8S"
    - ls $CI_PROJECT_DIR/k8s
    - kubectl apply -f $CI_PROJECT_DIR/k8s/staging/.
    - kubectl rollout restart deployments/alexey-borisov-app-staging
    - kubectl get pods
    - kubectl get svc
  only:
    - develop

deploy_production:
  stage: deploy_production
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl get pods
    - kubectl get nodes -o wide
    - echo "Deployment LOGIN-APP to K8S"
    - ls $CI_PROJECT_DIR/k8s
    - kubectl apply -f $CI_PROJECT_DIR/k8s/production/.
    - kubectl rollout restart deployments/alexey-borisov-app-production
    - kubectl get pods
    - kubectl get svc
  only:
    - main