image: docker:latest

variables:
  KUBE_ENV: "production" # название окружения в GitLab

before_script:
  - apk add --no-cache curl
  - curl -LO "https://github.com/bitnami/kubectl-bin/releases/download/v1.20.6/kubectl-linux-amd64" && chmod +x ./kubectl-linux-amd64 && mv ./kubectl-linux-amd64 /usr/local/bin/kubectl
  - echo "$KUBECONFIG" | base64 -d > /builds/$CI_PROJECT_PATH/kubeconfig.yaml
  - export KUBECONFIG="$PWD/kubeconfig.yaml"

stages:
  - build
  - test
  - deploy_staging
  - deploy_production

build:
  stage: build
  script:
    - docker build -t your-image-name:latest .

deploy:
  stage: deploy
  environment:
    name: production
    url: https://your-app-url.com
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml