apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eco-law-ingress
spec:
  rules:
    - host: xn--80acdkatfgh9abwig.xn--p1ai # алексейборисов.рф
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eco-law-service
                port:
                  number: 80