apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiYm9yaXNleSIsInBhc3N3b3JkIjoiZ2xwYXQtdXMtTW1WZGN6eGhLWWdTOHl2Sm8iLCJhdXRoIjoiWW05eWFYTmxlVHBuYkhCaGRDMTFjeTFOYlZaa1kzcDRhRXRaWjFNNGVYWktidz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-key
type: kubernetes.io/dockerconfigjson
